### PR TITLE
Disambiguate Pattern vs StringProtocol

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
FYI: @NCrusher

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
Oops. Sorry. Wrong @ncrusher.

FYI: @NCrusher74.

**Comment by NCrusher74** [comment]
I'm not sure what I should do here?

**Comment by SDGGiesbrecht** [comment]
Nothing. Just note that I’m fixing the bug you noticed.

**Comment by NCrusher74** [comment]
LOL okay thank you!

**Pull request merged**
